#!/usr/bin/env python3
# live_l1/core/clock.py
#
# Deterministic L1 Tick Clock
# - separates loop cadence from market feed
# - supports fixed tick ids
# - supports optional wall-clock pacing
# - ASCII-only

from __future__ import annotations

import time
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional


def _utc_now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.%fZ")


@dataclass(frozen=True)
class ClockTick:
    tick_id: int
    tick_started_utc: str
    monotonic_now: float


class TickClock:
    """
    Deterministic tick clock for L1.

    Modes:
    - decision_tick_seconds <= 0.0:
        no sleeping, emits ticks as fast as possible
    - decision_tick_seconds > 0.0:
        wall-clock paced ticks based on monotonic time

    Notes:
    - Tick ids are generated by the clock, not by the market feed.
    - UTC timestamps are generated centrally here for consistent observability.
    - This clock does not own stop conditions; the loop remains responsible
      for max_ticks / max_run_seconds / state.is_running.
    """

    def __init__(self, decision_tick_seconds: float = 0.0):
        try:
            dts = float(decision_tick_seconds)
        except Exception:
            dts = 0.0

        if dts < 0.0:
            dts = 0.0

        self.decision_tick_seconds = dts
        self._tick_id = 0
        self._next_deadline_monotonic: Optional[float] = None

    @property
    def tick_id(self) -> int:
        return self._tick_id

    def start(self) -> None:
        """
        Initializes the clock schedule.
        Safe to call once before the loop starts.
        """
        now_mono = time.monotonic()

        if self.decision_tick_seconds > 0.0:
            self._next_deadline_monotonic = now_mono
        else:
            self._next_deadline_monotonic = None

    def next_tick(self) -> ClockTick:
        """
        Advances the clock by exactly one tick and returns the tick metadata.
        """
        if self.decision_tick_seconds > 0.0:
            if self._next_deadline_monotonic is None:
                self._next_deadline_monotonic = time.monotonic()

            now_mono = time.monotonic()
            sleep_seconds = self._next_deadline_monotonic - now_mono
            if sleep_seconds > 0.0:
                time.sleep(sleep_seconds)

            tick_mono = time.monotonic()
            self._next_deadline_monotonic = tick_mono + self.decision_tick_seconds
        else:
            tick_mono = time.monotonic()

        self._tick_id += 1

        return ClockTick(
            tick_id=self._tick_id,
            tick_started_utc=_utc_now_iso(),
            monotonic_now=tick_mono,
        )