from typing import Any, Dict, Optional


class PnLEngine:

    def __init__(self):
        self.last_realized_pnl = 0.0

    def update(
        self,
        trade_event: Optional[Any],
        execution: Dict[str, Any],
    ) -> float:
        """
        Realized PnL only.

        Consumes LifecycleEvents generated by TradeLifecycleEngine.
        """

        if trade_event is None:
            return 0.0

        if getattr(trade_event, "event_type", None) != "TRADE_CLOSED":
            return 0.0

        pnl = float(getattr(trade_event, "realized_pnl", 0.0))

        self.last_realized_pnl = pnl

        return pnl

    def get_last_realized_pnl(self) -> float:
        return self.last_realized_pnl
