#!/usr/bin/env python3
# tools/compare_trade_analyses.py
# ASCII-only
#
# Compare two trade analysis CSV files that were generated by:
#   tools/analyze_trades.py --csv-out ...
#
# Usage:
#   python3 tools/compare_trade_analyses.py \
#       --a live_logs/long_auto_analysis.csv \
#       --b live_logs/short_auto_analysis.csv \
#       --label-a LONG \
#       --label-b SHORT
#
# Optional:
#   --csv-out live_logs/long_vs_short_comparison.csv

from __future__ import annotations

import argparse
import csv
import math
from statistics import mean, pstdev
from typing import Any


def _safe_float(value: Any, default: float = 0.0) -> float:
    try:
        if value is None:
            return default
        s = str(value).strip()
        if s == "":
            return default
        return float(s)
    except Exception:
        return default


def _load_rows(path: str) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    with open(path, "r", encoding="utf-8", newline="") as fh:
        reader = csv.DictReader(fh)
        for row in reader:
            rows.append(dict(row))
    return rows


def _profit_factor(pnls: list[float]) -> float:
    gross_profit = sum(p for p in pnls if p > 0.0)
    gross_loss_abs = abs(sum(p for p in pnls if p < 0.0))
    if gross_loss_abs == 0.0:
        if gross_profit > 0.0:
            return float("inf")
        return 0.0
    return gross_profit / gross_loss_abs


def _sharpe_like(pnl_pcts: list[float]) -> float:
    if len(pnl_pcts) < 2:
        return 0.0
    mu = mean(pnl_pcts)
    sigma = pstdev(pnl_pcts)
    if sigma <= 0.0:
        return 0.0
    return math.sqrt(len(pnl_pcts)) * (mu / sigma)


def _max_drawdown_from_equity(equity_values: list[float]) -> tuple[float, float]:
    if not equity_values:
        return 0.0, 0.0

    peak = equity_values[0]
    max_dd_abs = 0.0
    max_dd_pct = 0.0

    for eq in equity_values:
        if eq > peak:
            peak = eq
        dd_abs = peak - eq
        dd_pct = (dd_abs / peak) if peak > 0.0 else 0.0
        if dd_abs > max_dd_abs:
            max_dd_abs = dd_abs
        if dd_pct > max_dd_pct:
            max_dd_pct = dd_pct

    return max_dd_abs, max_dd_pct


def _summarize(path: str, label: str) -> dict[str, Any]:
    rows = _load_rows(path)

    if not rows:
        return {
            "label": label,
            "path": path,
            "num_trades": 0,
            "total_pnl": 0.0,
            "avg_pnl": 0.0,
            "winrate": 0.0,
            "avg_win": 0.0,
            "avg_loss": 0.0,
            "profit_factor": 0.0,
            "avg_duration_sec": 0.0,
            "final_equity": 0.0,
            "max_drawdown_abs": 0.0,
            "max_drawdown_pct": 0.0,
            "sharpe_like": 0.0,
        }

    pnls = [_safe_float(r.get("pnl"), 0.0) for r in rows]
    pnl_pcts = [_safe_float(r.get("pnl_pct"), 0.0) for r in rows]
    durations = [_safe_float(r.get("duration_sec"), 0.0) for r in rows]
    equities = [_safe_float(r.get("equity"), _safe_float(r.get("equity_after_trade"), 0.0)) for r in rows]

    wins = [p for p in pnls if p > 0.0]
    losses = [p for p in pnls if p <= 0.0]

    max_dd_abs, max_dd_pct = _max_drawdown_from_equity(equities)

    return {
        "label": label,
        "path": path,
        "num_trades": len(rows),
        "total_pnl": sum(pnls),
        "avg_pnl": mean(pnls) if pnls else 0.0,
        "winrate": (len(wins) / len(pnls)) if pnls else 0.0,
        "avg_win": mean(wins) if wins else 0.0,
        "avg_loss": mean(losses) if losses else 0.0,
        "profit_factor": _profit_factor(pnls),
        "avg_duration_sec": mean(durations) if durations else 0.0,
        "final_equity": equities[-1] if equities else 0.0,
        "max_drawdown_abs": max_dd_abs,
        "max_drawdown_pct": max_dd_pct,
        "sharpe_like": _sharpe_like(pnl_pcts),
    }


def _fmt_float(x: float, digits: int = 4) -> str:
    if math.isinf(x):
        return "inf"
    return f"{x:.{digits}f}"


def _winner(a: float, b: float, higher_is_better: bool = True) -> str:
    if abs(a - b) < 1e-12:
        return "TIE"
    if higher_is_better:
        return "A" if a > b else "B"
    return "A" if a < b else "B"


def _write_comparison_csv(path: str, a: dict[str, Any], b: dict[str, Any]) -> None:
    metrics = [
        ("num_trades", True),
        ("total_pnl", True),
        ("avg_pnl", True),
        ("winrate", True),
        ("avg_win", True),
        ("avg_loss", True),
        ("profit_factor", True),
        ("avg_duration_sec", False),
        ("final_equity", True),
        ("max_drawdown_abs", False),
        ("max_drawdown_pct", False),
        ("sharpe_like", True),
    ]

    with open(path, "w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(["metric", "label_a", "value_a", "label_b", "value_b", "winner"])
        for metric, hib in metrics:
            writer.writerow([metric, a["label"], a[metric], b["label"], b[metric], _winner(a[metric], b[metric], hib)])


def main() -> int:
    p = argparse.ArgumentParser(prog="compare_trade_analyses.py")
    p.add_argument("--a", required=True, help="first analysis CSV")
    p.add_argument("--b", required=True, help="second analysis CSV")
    p.add_argument("--label-a", default="A", help="label for first analysis")
    p.add_argument("--label-b", default="B", help="label for second analysis")
    p.add_argument("--csv-out", default="", help="optional comparison CSV output path")
    args = p.parse_args()

    a = _summarize(args.a, args.label_a)
    b = _summarize(args.b, args.label_b)

    print("---- ANALYSIS COMPARISON ----")
    print(f"A_label: {a['label']}")
    print(f"A_path: {a['path']}")
    print(f"B_label: {b['label']}")
    print(f"B_path: {b['path']}")
    print("")

    metrics = [
        ("num_trades", True, 0),
        ("total_pnl", True, 2),
        ("avg_pnl", True, 4),
        ("winrate", True, 4),
        ("avg_win", True, 4),
        ("avg_loss", True, 4),
        ("profit_factor", True, 4),
        ("avg_duration_sec", False, 2),
        ("final_equity", True, 2),
        ("max_drawdown_abs", False, 2),
        ("max_drawdown_pct", False, 4),
        ("sharpe_like", True, 4),
    ]

    for metric, higher_is_better, digits in metrics:
        av = a[metric]
        bv = b[metric]
        who = _winner(av, bv, higher_is_better)
        better = "A" if who == "A" else ("B" if who == "B" else "TIE")
        print(
            f"{metric}: "
            f"{a['label']}={_fmt_float(float(av), digits)} | "
            f"{b['label']}={_fmt_float(float(bv), digits)} | "
            f"better={better}"
        )

    csv_out = args.csv_out.strip()
    if csv_out != "":
        _write_comparison_csv(csv_out, a, b)
        print("")
        print(f"csv_out: {csv_out}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())